FROM amazoncorretto:17-al2-full //de que imagen partimos
MAINTAINER pameMora //dueño
COPY target/demo-0.0.1-SNAPSHOT.jar pamePortfolio-app.jar //copia empaquetado a github
ENTRYPOINT ["java", "-jar", "/pamePortfolio-app.jar"] // instruccion que se ejecuta primero